name: qiita_trend
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.1
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.63.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_web_auth_2: ^3.0.3
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  uuid: ^4.1.0
  webview_flutter: ^4.4.1
  auto_route: ^7.8.4
  riverpod_generator: ^2.3.3
  auto_route_generator: ^7.3.2
  uni_links: ^0.5.1
  flutter_inappwebview: ^5.8.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  # riverpod_lint: ^2.3.0
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_image.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
