// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9pQAoj5-ItQS5bJiv5Fb8uBR75IY1oQ',
    appId: '1:15475425750:web:37f0cbf53e0f9a507ce477',
    messagingSenderId: '15475425750',
    projectId: 'qiita-trends-c83e9',
    authDomain: 'qiita-trends-c83e9.firebaseapp.com',
    storageBucket: 'qiita-trends-c83e9.appspot.com',
    measurementId: 'G-XMK8L6M9HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmzjgq7d4RnA44rbMqkLmy4IvbJPjm1eU',
    appId: '1:15475425750:android:4b90ea6954a575ec7ce477',
    messagingSenderId: '15475425750',
    projectId: 'qiita-trends-c83e9',
    storageBucket: 'qiita-trends-c83e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj2VfFqPnivy5Npw1TwDvX4PFPrHCFyS0',
    appId: '1:15475425750:ios:1e2698736e765e667ce477',
    messagingSenderId: '15475425750',
    projectId: 'qiita-trends-c83e9',
    storageBucket: 'qiita-trends-c83e9.appspot.com',
    iosBundleId: 'com.example.qiitaTrend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj2VfFqPnivy5Npw1TwDvX4PFPrHCFyS0',
    appId: '1:15475425750:ios:4b39b9bcabd1f5a27ce477',
    messagingSenderId: '15475425750',
    projectId: 'qiita-trends-c83e9',
    storageBucket: 'qiita-trends-c83e9.appspot.com',
    iosBundleId: 'com.example.qiitaTrend.RunnerTests',
  );
}
